name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y libgsl-dev

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Compile
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run regression tests
      run: |
        ./scripts/RunRegressionTests.sh
        if [ $? -eq 0 ]; then
          echo "Regression tests completed successfully"
          exit 0
        else
          echo "Regression tests failed"
          exit 1
        fi

    - name: Run unit tests
      run: |
        ./build/bin/Covid19EERAModel-unit_tests
        if [ $? -eq 0 ]; then
          echo "Unit tests completed successfully"
          exit 0
        else
          echo "Unit tests failed"
          exit 1
        fi
    - name: Run Cpp Check
      run: |
         echo "Running CppCheck on header files in 'src'"
         for i in src/*.h; do cppcheck --language=c++ $i; done
         echo "Running CppCheck on source files in 'src'"
         for i in src/*.cpp; do cppcheck --language=c++ $i; done
         echo "Running CppCheck on source files in 'test/unit'"
         for i in test/unit/*.cpp; do cppcheck --language=c++ $i; done

