name: Covid19EERAModel

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.config.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
                os: ['ubuntu-latest', 'macos-latest']
                config: [{
                            compiler: gcc,
                            compilerpp: g++
                        },
                        {
                            compiler: clang,
                            compilerpp: clang++
                        }
                        ]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -y libgsl-dev clang lcov cppcheck
      if: matrix.os == 'ubuntu-latest'

    - name: Install Brew (Mac OS X)
      run : /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      if: matrix.os == 'macos-latest'

    - name: Install Dependencies (Mac OS X)
      run : brew update && brew install gsl cppcheck lcov
      if: matrix.os == 'macos-latest'

    - name: Compile
      env:
              CC: ${{ matrix.config.compiler }}
              CXX: ${{ matrix.config.compilerpp }}
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run regression tests
      run: |
        ./scripts/RunRegressionTests.sh
        if [ $? -eq 0 ]; then
          echo "Regression tests completed successfully"
          exit 0
        else
          echo "Regression tests failed"
          exit 1
        fi

    - name: Run unit tests
      run: |
        ./build/bin/Covid19EERAModel-unit_tests
        if [ $? -eq 0 ]; then
          echo "Unit tests completed successfully"
          exit 0
        else
          echo "Unit tests failed"
          exit 1
        fi
    - name: Run Cpp Check with internal parser
      run: |
         echo "Running CppCheck on files in 'src' with internal parser"
         for i in src/*.h src/*.cpp test/unit/*.cpp; do 
           if cppcheck --language=c++ --std=c++11 --error-exitcode=1 $i; then
             continue
           else
             exit 1
           fi
         done

    - name: Run GCov and LCov Code Coverage
      run : |
            cd build
            make coverage
  
