name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y libgsl-dev

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Compile
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run regression tests
      run: |
        ./scripts/RunRegressionTests.sh
        if [ $? -eq 0 ]; then
          echo "Regression tests completed successfully"
          exit 0
        else
          echo "Regression tests failed"
          exit 1
        fi

    - name: Run unit tests
      run: |
        ./build/bin/Covid19EERAModel-unit_tests
        if [ $? -eq 0 ]; then
          echo "Unit tests completed successfully"
          exit 0
        else
          echo "Unit tests failed"
          exit 1
        fi
    - name: Run Cpp Check with internal parser
      run: |
         echo "Running CppCheck on files in 'src' with internal parser"
         for i in src/*.h src/*.cpp test/unit/*.cpp; do 
           if cppcheck --language=c++ --std=c++11 --error-exitcode=1 $i; then
             continue
           else
             exit 1
           fi
         done

